### ISSUE TITLE
Send File Did not Working 

### ISSUE THREAD

**Issue by Yohanes-arch** [Kalebu/alright#116]
Hi, so just straightforward, the send_file function did not work for me, it just showed the previews of the file but didn't send the file 
Here is the screenshot

![Screenshot 2023-03-24 124856](https://user-images.githubusercontent.com/74139916/227435577-b69c9f4c-7eb2-4662-a319-2ff7ae0f61fb.png)

The process stops right here and nothing happens when I keep waiting. This happens when I use the CLI, but the send_message is working properly. Then I tried this command through a python script, but both didn't work.

**Comment by Ceserax** [comment]
Same issue here. It stops and waits when it has to click and send the picture or video. Never had that problem but since a week or so this happens. Could it be the chrome driver version upgrade recently?

---------------------------
from alright import WhatsApp
messenger = WhatsApp()
numbers = ['+31xxxxxxxxx']
for number in numbers:
    messenger.find_user(number)

    messenger.send_picture(
        "/Users/newfolder/Epex_Michel.png",'day-ahead prices')
-----------------------------
This is where it stops:

<img width="726" alt="Screen Shot 2023-03-29 at 22 02 19" src="https://user-images.githubusercontent.com/45273848/228657636-bc01c7ee-9db9-48e1-bb74-a0a8697b0711.png">

And this is the output:
<img width="1197" alt="Screen Shot 2023-03-29 at 22 12 42" src="https://user-images.githubusercontent.com/45273848/228659721-f14ad16e-573b-4506-96fe-0982b968f327.png">

Btw. Messages are working fine.

Hope you can help

**Comment by FrancescoLucarini** [comment]
Me too same problem, also tried with keyboard or pyautogui to press enter, but not sending images

**Comment by FrancescoLucarini** [comment]
Any update or someone knows another solution?

**Comment by dellinfa** [comment]
same problem for me with send_picture

**Comment by Harsh-Gangwal** [comment]
Yes, I am facing the same issue. I think the XPath of text box and the sent button have to be modified to the updated version of google chrome. Because send_message function is working perfectly.

**Comment by Harsh-Gangwal** [comment]
Yes, I am facing the same issue. I think the XPath of the text box and the sent button have to be modified to the updated version of google chrome. Because send_message function is working perfectly.

**Comment by dellinfa** [comment]
> harry It's the same for me. Send_message work perfectly..

**Comment by allesman** [comment]
By the way, how are you guys even sending a message when find contact isn't working. Or does it work for you?

**Comment by aeris07** [comment]
Hello, @farcas @dellinfa @allesman @FrancescoLucarini @Yohanes-arch @harry-py-bot 

web.whatsapp.com has changed html structure recently, that's why a modification needed in the code, 
You can replace __init__.py of alright code with the updated document in the attachment,
Hope it helps.
Best regards...

**Comment by FrancescoLucarini** [comment]
Thanks so much!

**Comment by Kalebu** [comment]
> `Hello,` @farcas @dellinfa @allesman @FrancescoLucarini @Yohanes-arch @harry-py-bot
> 
> web.whatsapp.com has changed html structure recently, that's why a modification needed in the code, You can replace **init**.py of alright code with the updated document in the attachment, It works for sending messages, attachments and pictures. I haven't tried other functions by the way. Hope it helps. Best regards... [**init**.zip](https://github.com/Kalebu/alright/files/11364232/__init__.zip)

Thank you for this @aeris07, I launched a product on early April I have been crazy busy 

Will replace the code in the main repository and then push it to PyPI. 

Will keep you guys updated

**Comment by psd-psd** [comment]
Even I am facing the same issue
