### ISSUE TITLE
how to disable open WhatsApp application

### ISSUE THREAD

**Issue by madzul** [Kalebu/alright#24]
everytime i run the code (from the examples), a web browser (Chrome) opened and then ask me to open whatsapp application (https://api.whatsapp.com wants to open this application)
if I canceled, then the browser do nothing, otherwise the whatsapp application is opened and alright gave me error:
`raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable`

**Comment by VanshKela** [comment]
Yes can anyone fix this? I guess problem is with wa.me/ link as it is trying to open api.whatsapp.com

**Comment by Fahad-Alsaidi** [comment]
I have the same problem

**Comment by mlicenblat** [comment]
Hi, I have the same problem.
Sometimes i close the application on every message and it works but i want to know how to do that without this problem with the desktop application.
Any idea? I suppose when you access api.whatsapp.com always tries to use the application

**Comment by theCJMan** [comment]
Hi all, I thought I left a message to say I found the problem and am looking into it to fix it...
But i do not see my comment So here it is now...

The problem is that self.suffix_link = "https://wa.me/" is causing the desktop app to open, or rather causing the browser to ask if it should open the desktop app.

If you call web.open(f"https://web.whatsapp.com/send?phone={phone_no}&text={quote(message)}") this does NOT cause the browser to ask if it should open the desktop app

So I generated an additional send_message1 in __init__.py code file, I have tried to add many comments in the code so it should be clear
`
    def send_message1(self, mobile: str, message: str):
        """ CJM - 20220419:
            Send WhatsApp Message With Different URL, NOT using https://wa.me/ to prevent WhatsApp Desktop to open
            Also include the Number we want to send to """
        try:
            # Browse to a "Blank" message state
            self.browser.get(f"https://web.whatsapp.com/send?phone={mobile}&text")

            # This is the XPath of the message textbox
            inp_xpath = (
                '//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[2]'
            )
            # This is the XPath of the "ok button" if the number was not found
            nr_not_found_xpath = (
                '//*[@id="app"]/div/span[2]/div/span/div/div/div/div/div/div[2]/div/div'
            )

            # If the number is NOT a WhatsApp number then there will be an OK Button, not the Message Textbox
            # Test for both situations -> find_elements returns a List
            ctrl_element = self.wait.until(
                lambda ctrl_self:
                    ctrl_self.find_elements(By.XPATH, nr_not_found_xpath) or
                    ctrl_self.find_elements(By.XPATH, inp_xpath)
            )
            # Iterate through the list of elements to test each if they are a textBox or a Button
            for i in ctrl_element:
                if i.aria_role == 'textbox':
                    # This is a WhatsApp Number -> Send Message
                    i.send_keys(message + Keys.ENTER)
                    msg = f"Message sent successfully to {self.mobile}"

                elif i.aria_role == 'button':
                    # This is NOT a WhatsApp Number -> Press enter and continue
                    i.send_keys(Keys.ENTER)
                    msg = f"Not a WhatsApp Number {self.mobile}"

        except (NoSuchElementException, Exception) as bug:
            print(bug)
            msg = f"Failed to send a message to {self.mobile}"

        finally:
            print(msg)
`

And then my Example code is reading a CSV file and sending WhatsApp messages to them one by one, In South Africa (+27)  our mobile numbers is only 10 digits starting with a 0 e.g. 0790445672
`
from alright import WhatsApp
import pandas as pd

msg = "Kiss"

messenger = WhatsApp()

df = pd.read_csv("DataFile\contacts.csv")
#Conver the data to String
df['Mobile Phone'] = df['Mobile Phone'].astype(str)
df['Mobile Phone'] = df['Mobile Phone'].str.replace(' ', '')
for i, row in df.iterrows():
    mobNum = row['Mobile Phone']
    if len(mobNum) < 10:
        #Do nothing
        print("Number to short " + mobNum)
    elif (len(mobNum) == 10) and (mobNum[0] == '0'):
        #Add Country Code
        mobNum = '27' + mobNum[1:]
        messenger.send_message1(mobNum, msg)
    elif len(mobNum) >= 10:
        #Assume Country Code already in number
        messenger.send_message1(mobNum, msg)
`
