### ISSUE TITLE
Simultaneous messaging to multiple contacts

### ISSUE THREAD

**Issue by AtomicNess123** [Kalebu/alright#85]
Excellent code. Is it possible to send a message to multiple contacts simultaneously?

**Comment by Kalebu** [comment]
Hi @AtomicNess123 

Since `Alright` works by controlling the browser and not API integration, you can only send one message at a time but not concurrently, If you're sending to multiple contacts, the current best approach is to do it with a `for-loop` as shown below;

```python
>>> from alright import WhatsApp
>>> messenger = WhatsApp()
>>> numbers = ['2557xxxxxx', '2557xxxxxx', '....']
>>> for number in numbers:
        messenger.find_user(number)
        messenger.send_message("I wish you a Merry X-mass and Happy new year ")
```

Hope that answers your question

**Comment by AtomicNess123** [comment]
Thanks, of course, with a loop! Thanks!

**Comment by Kalebu** [comment]
You're welcome @AtomicNess123
